export const Books = [
  {
      "id": "1",
      "author": "Isaac Asimov",
      "country": "USA",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/d/d9/Foundation_-_Isaac_Asimov_%28Gnome_1951%29.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Foundation_(Asimov_novel)",
      "pages": 255,
      "title": "Foundation",
      "year": 1951,
      "rating": 4,
      "category": "Sci-Fi",
      "status": "Popular",
      "description": "A groundbreaking science fiction novel that introduces the concept of psychohistory, a mathematical sociology that predicts the future of large populations."
  },
  {
      "id": "2",
      "author": "Philip K. Dick",
      "country": "USA",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/DoAndroidsDream.png/380px-DoAndroidsDream.png",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Do_Androids_Dream_of_Electric_Sheep%3F",
      "pages": 210,
      "title": "Do Androids Dream of Electric Sheep?",
      "year": 1968,
      "rating": 3.9,
      "category": "Sci-Fi",
      "status": "Trending",
      "description": "A dystopian novel set in a post-apocalyptic world, exploring the themes of humanity, empathy, and the nature of consciousness through the story of a bounty hunter tasked with 'retiring' rogue androids."
  },
  {
      "id": "3",
      "author": "Arthur C. Clarke",
      "country": "UK",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/2001:_A_Space_Odyssey",
      "pages": 296,
      "title": "2001: A Space Odyssey",
      "year": 1968,
      "rating": 4.7,
      "category": "Sci-Fi",
      "status": "Popular",
      "description": "A seminal work of science fiction that explores themes of evolution, technology, and artificial intelligence through the journey of a spacecraft to Jupiter."
  },
  {
      "id": "4",
      "author": "William Shakespeare",
      "country": "England",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Edwin_Booth_Hamlet_1870.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Hamlet",
      "pages": 342,
      "title": "Hamlet",
      "year": 1603,
      "rating": 4.3,
      "category": "Non-Fiction",
      "status": "Trending",
      "description": "A tragedy that tells the story of Prince Hamlet seeking revenge against his uncle, who has murdered Hamlet's father, taken the throne, and married Hamlet's mother."
  },
  {
      "id": "5",
      "author": "Tennessee Williams",
      "country": "USA",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/6/66/StreetcarNamedDesire.JPG",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/A_Streetcar_Named_Desire",
      "pages": 128,
      "title": "A Streetcar Named Desire",
      "year": 1947,
      "rating": 3.8,
      "category": "Non-Fiction",
      "status": "Trending",
      "description": "A powerful play that explores themes of desire, mental illness, and the fragility of human relationships through the story of Blanche DuBois and her tragic encounter with Stanley Kowalski."
  },
  {
      "id": "6",
      "author": "George Orwell",
      "country": "UK",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/5/51/1984_first_edition_cover.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/1984_(novel)",
      "pages": 328,
      "title": "1984",
      "year": 1949,
      "rating": 3.9,
      "category": "Fiction",
      "status": "Popular",
      "description": "A dystopian novel that presents a terrifying vision of a totalitarian future controlled by the Party and its leader, Big Brother, where surveillance and thought control are the norm."
  },
  {
      "id": "7",
      "author": "Harper Lee",
      "country": "USA",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/1280px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird",
      "pages": 281,
      "title": "To Kill a Mockingbird",
      "year": 1960,
      "rating": 4.2,
      "category": "Fiction",
      "status": "Trending",
      "description": "A coming-of-age story set in the Deep South during the 1930s, it deals with serious issues such as racial injustice and moral growth through the eyes of a young girl, Scout Finch."
  },
  {
      "id": "8",
      "author": "Malcolm Gladwell",
      "country": "Canada",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/e/ec/Outliers_%28book_cover%29.png",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Outliers:_The_Story_of_Success",
      "pages": 309,
      "title": "Outliers: The Story of Success",
      "year": 2008,
      "rating": 4.3,
      "category": "Non-Fiction",
      "status": "Trending",
      "description": "An exploration of the factors that contribute to high levels of success, emphasizing the importance of context, culture, and timing over individual talent."
  },
  {
      "id": "10",
      "author": "F. Scott Fitzgerald",
      "country": "USA",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/1024px-The_Great_Gatsby_Cover_1925_Retouched.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Great_Gatsby",
      "pages": 180,
      "title": "The Great Gatsby",
      "year": 1925,
      "rating": 4.8,
      "category": "Fiction",
      "status": "Trending",
      "description": "A classic American novel that critiques the American Dream through the tragic story of Jay Gatsby and his obsession with Daisy Buchanan in the Roaring Twenties."
  },
  {
      "id": "11",
      "author": "Jane Austen",
      "country": "UK",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/PrideAndPrejudiceTitlePage.jpg/440px-PrideAndPrejudiceTitlePage.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice",
      "pages": 279,
      "title": "Pride and Prejudice",
      "year": 1813,
      "rating": 4.5,
      "category": "Non-Fiction",
      "status": "Trending",
      "description": "A romantic novel that explores themes of class, marriage, and social norms in early 19th-century England through the story of Elizabeth Bennet and Mr. Darcy."
  },
  {
      "id": "12",
      "author": "J.K. Rowling",
      "country": "UK",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Sorcerer%27s_Stone",
      "pages": 309,
      "title": "Harry Potter and the Sorcerer's Stone",
      "year": 1997,
      "rating": 4.4,
      "category": "Fiction",
      "status": "Trending",
      "description": "The first book in the Harry Potter series, it follows a young boy who discovers he is a wizard and attends Hogwarts School of Witchcraft and Wizardry."
  },
  {
      "id": "13",
      "author": "Mark Twain",
      "country": "USA",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Tom_Sawyer_1876_frontispiece.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Adventures_of_Tom_Sawyer",
      "pages": 274,
      "title": "The Adventures of Tom Sawyer",
      "year": 1876,
      "rating": 4.3,
      "category": "Fiction",
      "status": "Trending",
      "description": "A novel about a young boy's adventures along the Mississippi River, highlighting themes of childhood, friendship, and moral growth."
  },
  {
      "id": "14",
      "author": "Stephen Hawking",
      "country": "UK",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/a/a3/BriefHistoryTime.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/A_Brief_History_of_Time",
      "pages": 256,
      "title": "A Brief History of Time",
      "year": 1988,
      "rating": 4.9,
      "category": "Non-Fiction",
      "status": "Trending",
      "description": "An accessible introduction to cosmology, exploring the nature of time, black holes, and the universe, aimed at readers without a scientific background."
  },

]

